# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://128.40.193.25:8086"]
  token = "$INFLUX_TOKEN"
  organization = "UCL-CE"
  bucket = "CE_yeo"


[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt.cetools.org:1883"]
  topics = ["yeo/+/acoupi"]
  data_format = "json_v2"

# --- BLOCK 1: THE BIRD DETECTOR ---
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "acoupi_detections"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "detections" # This block ONLY triggers if this path exists
      disable_prepend_keys = true
      tags = ["label"]
      [inputs.mqtt_consumer.json_v2.object.fields]
        label = "tags.0.tag.value"
        confidence = "detection_score"

  # --- BLOCK 2: THE HEARTBEAT SENSOR ---
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "acoupi_heartbeat"
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "@this"
      # We use 'included_keys' to capture the heartbeat fields
      included_keys = ["deployment_name", "latitude", "longitude"]
      tags = ["deployment_name"]